version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: postgres_data
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: people
    ports:
      - "5433:5432"
